(in-package :cl-tk)

(defun test-button ()
  (with-tk ()
    (let ((stop nil))
      (tcl "ttk::button" ".b" :text "Exit ☻" :command (event-handler* (setf stop t)))
      (tcl "pack .b")
      (loop :while (alive-p)
            :do (doevent t)
            :do (when stop (destroy))))
    (mainloop)))
